# Netlify Configuration for KOA Estudio
# This file configures security headers, redirects, and build settings

[build]
  publish = "dist"
  command = "npm run build"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking
    X-Frame-Options = "DENY"

    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"

    # Enable XSS protection
    X-XSS-Protection = "1; mode=block"

    # Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Disable potentially dangerous features
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

    # Content Security Policy
    # Allows your app and Supabase connections
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://gjvikgrcvtkvcnojrtjf.supabase.co;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https: blob:;
      font-src 'self' data:;
      connect-src 'self' https://gjvikgrcvtkvcnojrtjf.supabase.co wss://gjvikgrcvtkvcnojrtjf.supabase.co;
      media-src 'self' blob:;
      object-src 'none';
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self';
    """

# SPA redirects - all routes go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
